spring.application.name=stayhub-Reservation

server.port=8081
grpc.server.port=9091

spring.datasource.url=jdbc:h2:file:./data/testdb_Reservation
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console-Reservation

springdoc.api-docs.path=/api-docs-Reservation
springdoc.swagger-ui.path=/swagger-ui.html

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

logging.level.org.springframework=INFO
logging.level.com.Angelh0.stayhub=DEBUG
